language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
addons:
  chrome: stable
node_js:
  - stable
  - '13'
before_install:
#  - sh ./build/setup_puppeteer.sh
install:
  - npm install lerna
  - npm run bootstrap
script:
  - npm run build
  - npm run test
  - npm run report
